// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU9NgS-IcQVwBeR8sMBuk-F6_I1WHtKAE',
    appId: '1:145780511378:web:11bb77b70d16ce23808c4b',
    messagingSenderId: '145780511378',
    projectId: 'movies-b6896',
    authDomain: 'movies-b6896.firebaseapp.com',
    storageBucket: 'movies-b6896.appspot.com',
    measurementId: 'G-EYRPSS2060',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGgsghveWTyoBQDDG0JJ4ewUUJrzlSI4U',
    appId: '1:145780511378:android:057e71ca80d10b3c808c4b',
    messagingSenderId: '145780511378',
    projectId: 'movies-b6896',
    storageBucket: 'movies-b6896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYzb9FGpt0fzyGMtz6YLNLtgCrdmuH8Go',
    appId: '1:145780511378:ios:9db1dedaf15b32c9808c4b',
    messagingSenderId: '145780511378',
    projectId: 'movies-b6896',
    storageBucket: 'movies-b6896.appspot.com',
    iosBundleId: 'com.eslamfares.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYzb9FGpt0fzyGMtz6YLNLtgCrdmuH8Go',
    appId: '1:145780511378:ios:9db1dedaf15b32c9808c4b',
    messagingSenderId: '145780511378',
    projectId: 'movies-b6896',
    storageBucket: 'movies-b6896.appspot.com',
    iosBundleId: 'com.eslamfares.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU9NgS-IcQVwBeR8sMBuk-F6_I1WHtKAE',
    appId: '1:145780511378:web:3aa3015efc9281f0808c4b',
    messagingSenderId: '145780511378',
    projectId: 'movies-b6896',
    authDomain: 'movies-b6896.firebaseapp.com',
    storageBucket: 'movies-b6896.appspot.com',
    measurementId: 'G-HXJ5LYST5V',
  );
}
